# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f3c29f9b4be48562150125208962a61d8b633879ff821fc1c01c7073d45190ddfcbacf0181de258234ddfc701b39875c885ae172d2cbc79b89602ffd6f2bf61

test:
  secret_key_base: 5b99b01d2aeb4f9c289ecf31a364bae82b97326b5be9bf5ef12cbd640c2ec1bc8621b4cbb0e4eae8ffdd2c09dfcc81764079994b65ba92091ee4935a1543b95b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
